<?php
namespace app\model;
use think\Model;
class admin_info extends Model
{
    protected $name = 'tanyou';
    protected $table = 'admin_info';

    protected $admin_info=[
        'aUID'  =>  'int',
        'aPwd'  =>  'varchar',
        'aName' =>  'varchar',
        'aBirth'=>  'date',
        'aSex'  =>  'varchar',
        'aTel'  =>  'varchar',
        'aPhoto'=>  'mediumblob',
        'aUser_name' => 'varchar'
    ];
    protected  static  function  init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}