<?php
namespace app\model;
use think\Model;

class consumer_info extends Model
{
    protected $name = 'tanyou';
    protected $table = 'consumer_info';
    protected $consumer_info =[
        'cUID'      =>  'int',
        'cPwd'      =>  'varchar',
        'cName'     =>  'varchar',
        'cBirth'    =>  'datetime',
        'cSex'      =>  'varchar',
        'cTel'      =>  'varchar',
        'cPhoto' => 'mediumblob',
        'cID'      =>  'varchar',
        'cUser_name' => 'varchar'
    ];
    protected  static  function  init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}